In [1]:
# # 01 — Load and Inspect

# This notebook loads the CSV file using the project preprocessing module.
# It inspects:
# • metadata
# • frame indices
# • timestamps
# • position arrays
# quaternion arrays

In [2]:
import os
import numpy as np
import pandas as pd

# Make sure src/ is on the Python path
import sys
PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
SRC_PATH = os.path.join(PROJECT_ROOT, "src")
if SRC_PATH not in sys.path:
    sys.path.insert(0, SRC_PATH)

from config import CONFIG
from preprocessing import parse_optitrack_csv

print("Paths configured.")

Paths configured.


In [3]:
# Path loaded from config.yaml
DATA_DIR = os.path.join(PROJECT_ROOT, CONFIG['data_dir'])
CSV_PATH = os.path.join(DATA_DIR, CONFIG['current_csv'])

print("CSV path:", CSV_PATH)

CSV path: /Users/drorhazan/Documents/untitled folder/Gaga-mocap-Kinematics/data/734/T1/734_T1_P1_R1_Take 2025-12-01 02.18.27 PM.csv


In [4]:
import json

SCHEMA_PATH = os.path.join(PROJECT_ROOT, "config", "skeleton_schema.json")

if os.path.exists(SCHEMA_PATH):
    with open(SCHEMA_PATH, "r") as f:
        schema = json.load(f)
    print("Schema loaded:", SCHEMA_PATH)
else:
    schema = None
    print("Schema file not found — you must create or provide one.")

Schema loaded: /Users/drorhazan/Documents/untitled folder/Gaga-mocap-Kinematics/config/skeleton_schema.json


In [5]:
frame_idx, time_s, pos_mm, q_global, loader_report = parse_optitrack_csv(
    CSV_PATH,
    schema
)

print("CSV parsed successfully.")

CSV parsed successfully.


In [6]:
# # Run this in a new cell to inspect the raw file structure
# with open(CSV_PATH, 'r', encoding='utf-8', errors='ignore') as f:
#     print("--- FIRST 10 LINES OF CSV ---")
#     for i in range(10):
#         print(repr(f.readline())) # repr() shows us hidden characters like \t or \r

In [7]:
import pprint
pprint.pprint(loader_report)

{'data_quality': {'nan_position_percent': '0.00%',
                  'nan_rotation_percent': '0.00%'},
 'duration_sec': np.float64(256.641667),
 'file_path': '/Users/drorhazan/Documents/untitled '
              'folder/Gaga-mocap-Kinematics/data/734/T1/734_T1_P1_R1_Take '
              '2025-12-01 02.18.27 PM.csv',
 'fps_estimated': np.float64(120.00480019200238),
 'segments_expected': 51,
 'segments_found_count': 51,
 'segments_found_list': ['Hips',
                         'Spine',
                         'Spine1',
                         'Neck',
                         'Head',
                         'LeftShoulder',
                         'LeftArm',
                         'LeftForeArm',
                         'LeftHand',
                         'LeftHandThumb1',
                         'LeftHandThumb2',
                         'LeftHandThumb3',
                         'LeftHandIndex1',
                         'LeftHandIndex2',
                         'LeftHandIndex3'

In [8]:
print("Frame count:", len(frame_idx))
print("Time array shape:", time_s.shape)
print("Positions array shape:", pos_mm.shape)   # (T, J, 3)
print("Quaternions array shape:", q_global.shape)  # (T, J, 4)

Frame count: 30798
Time array shape: (30798,)
Positions array shape: (30798, 51, 3)
Quaternions array shape: (30798, 51, 4)


In [9]:
print("First 10 timestamps:", time_s[:10])
print("Last timestamp:", time_s[-1])
print("Effective FPS estimate:", 1.0 / np.median(np.diff(time_s)))

First 10 timestamps: [0.       0.008333 0.016667 0.025    0.033333 0.041667 0.05     0.058333
 0.066667 0.075   ]
Last timestamp: 256.641667
Effective FPS estimate: 120.00480019200238


In [10]:
pos_missing = np.isnan(pos_mm).sum()
quat_missing = np.isnan(q_global).sum()

print("Missing position values:", pos_missing)
print("Missing quaternion values:", quat_missing)

Missing position values: 0
Missing quaternion values: 0


In [11]:
print("First frame positions (mm):")
print(pos_mm[0])

print("\nFirst frame quaternions (xyzw):")
print(q_global[0])

First frame positions (mm):
[[ 187.730682  911.314148  486.986908]
 [ 187.269012  993.285889  491.222076]
 [ 186.28952  1206.927124  507.944153]
 [ 187.844315 1427.659058  531.252197]
 [ 190.616821 1563.211548  562.815552]
 [ 223.977722 1376.568604  525.497314]
 [ 381.551422 1405.065796  514.968994]
 [ 591.244751 1274.743408  561.910278]
 [ 775.357849 1150.450562  632.740112]
 [ 804.430054 1110.539062  650.147888]
 [ 831.472839 1117.861328  656.57074 ]
 [ 855.837463 1120.550903  654.935913]
 [ 874.456421 1121.134766  616.255493]
 [ 906.956238 1106.079834  592.01001 ]
 [ 920.486511 1094.888306  579.385986]
 [ 862.989624 1127.403442  594.523193]
 [ 901.296509 1114.131714  569.622742]
 [ 921.011536 1104.558228  555.725586]
 [ 847.068115 1134.726318  575.698303]
 [ 883.652405 1126.137451  554.284363]
 [ 901.99231  1122.029053  543.586182]
 [ 831.048645 1142.102661  556.687683]
 [ 861.129089 1138.369751  539.999207]
 [ 876.333191 1138.569702  531.746033]
 [ 151.260941 1377.501465  521.51263

In [12]:
from skeleton_defs import SKELETON_HIERARCHY

def validate_hierarchy_and_build_map(found_joints_list, strict_mode=True):
    """
    Quality Gate:
    1. Checks if ALL joints defined in SKELETON_HIERARCHY exist in the data.
    2. Builds the final kinematics mapping dictionary.
    3. Throws a CRITICAL ERROR if strict_mode is True and any joint is missing.
    """
    
    print(f"\n{'='*20} HIERARCHY VALIDATION REPORT {'='*20}")
    print(f"Strict Mode: {strict_mode}\n")
    
    kinematics_map = {}
    missing_joints = []
    
    
    found_set = set(found_joints_list)
    
 
    for segment, info in SKELETON_HIERARCHY.items():
        parent = info['parent']
        angle_name = info['angle_name']
        
       
        if segment not in found_set:
            print(f"[FAIL] ❌ Segment Missing: {segment}")
            missing_joints.append(segment)
            continue
            
       
        if parent is not None and parent not in found_set:
            print(f"[FAIL] ❌ Parent Missing for {segment}: {parent}")
            missing_joints.append(f"{segment}_parent_{parent}")
            continue

        # 3. בניית המיפוי להמשך
        status = "Global" if parent is None else f"Rel: {parent}"
        print(f"[PASS] ✅ {segment:<15} -> {status:<15} => Output: '{angle_name}'")
        
        kinematics_map[segment] = {
            "parent": parent,
            "angle_name": angle_name,
            "is_global": (parent is None)
        }

    print(f"\n{'='*60}")
    
 
    if len(missing_joints) > 0:
        error_msg = f"CRITICAL VALIDATION ERROR: Missing {len(missing_joints)} required joints: {missing_joints}"
        if strict_mode:
            raise ValueError(error_msg)
        else:
            print(f"WARNING: {error_msg}")
    else:
        print("SUCCESS: Full skeleton hierarchy validated successfully.")
        
    return kinematics_map


try:
    kinematics_targets = validate_hierarchy_and_build_map(
        loader_report['segments_found_list'], 
        strict_mode=True 
    )
    print("\nKinematics Map Created Ready for Processing.")
except ValueError as e:
    print(f"\n⛔ STOPPING EXECUTION: {e}")


==================== HIERARCHY VALIDATION REPORT ====================
Strict Mode: True

[PASS] ✅ Hips            -> Global          => Output: 'Pelvis_Global_Orientation (World Space)'
[PASS] ✅ Spine           -> Rel: Hips       => Output: 'Lumbar_Angle'
[PASS] ✅ Spine1          -> Rel: Spine      => Output: 'Thoracic_Angle'
[PASS] ✅ Neck            -> Rel: Spine1     => Output: 'Neck_Base_Angle'
[PASS] ✅ Head            -> Rel: Neck       => Output: 'Head_Angle'
[PASS] ✅ LeftUpLeg       -> Rel: Hips       => Output: 'LeftHip_Angle'
[PASS] ✅ LeftLeg         -> Rel: LeftUpLeg  => Output: 'LeftKnee_Angle'
[PASS] ✅ LeftFoot        -> Rel: LeftLeg    => Output: 'LeftAnkle_Angle'
[PASS] ✅ LeftToeBase     -> Rel: LeftFoot   => Output: 'LeftToe_Angle'
[PASS] ✅ RightUpLeg      -> Rel: Hips       => Output: 'RightHip_Angle'
[PASS] ✅ RightLeg        -> Rel: RightUpLeg => Output: 'RightKnee_Angle'
[PASS] ✅ RightFoot       -> Rel: RightLeg   => Output: 'RightAnkle_Angle'
[PASS] ✅ RightToeBase   

In [13]:
# --- Save parsed data for Step 02 ---
import os

# 1. Create Output Directory
DERIV_01 = os.path.join(PROJECT_ROOT, CONFIG['derivatives_dir'], "step_01_parse")
os.makedirs(DERIV_01, exist_ok=True)

# 2. Convert raw arrays to DataFrame for saving
# We need to flatten the 3D arrays (Frames, Joints, 3/4) into 2D columns
flattened_data = {
    "frame_idx": frame_idx,
    "time_s": time_s
}

joint_names = schema['joint_names']

for i, name in enumerate(joint_names):
    # Save Position (X, Y, Z)
    flattened_data[f"{name}__px"] = pos_mm[:, i, 0]
    flattened_data[f"{name}__py"] = pos_mm[:, i, 1]
    flattened_data[f"{name}__pz"] = pos_mm[:, i, 2]
    
    # Save Rotation (X, Y, Z, W)
    flattened_data[f"{name}__qx"] = q_global[:, i, 0]
    flattened_data[f"{name}__qy"] = q_global[:, i, 1]
    flattened_data[f"{name}__qz"] = q_global[:, i, 2]
    flattened_data[f"{name}__qw"] = q_global[:, i, 3]

df_export = pd.DataFrame(flattened_data)

# 3. Save to Parquet
run_id = os.path.splitext(os.path.basename(CSV_PATH))[0]
out_path = os.path.join(DERIV_01, f"{run_id}__parsed_run.parquet")

df_export.to_parquet(out_path, index=False)

print(f"✅ Data saved successfully to:\n{out_path}")

✅ Data saved successfully to:
/Users/drorhazan/Documents/untitled folder/Gaga-mocap-Kinematics/derivatives/step_01_parse/734_T1_P1_R1_Take 2025-12-01 02.18.27 PM__parsed_run.parquet


In [14]:
import pandas as pd
import json
import os
import numpy as np

# --- 1. Build DataFrame ---
# שימוש ב-joints_found מתוך ה-loader_report
joints_found = loader_report['segments_found_list']

flattened_data = {
    'frame_idx': frame_idx,
    'time_s': time_s
}

for j_idx, joint_name in enumerate(joints_found):
    # Position (mm) - Mapping to __px, __py, __pz
    flattened_data[f'{joint_name}__px'] = pos_mm[:, j_idx, 0]
    flattened_data[f'{joint_name}__py'] = pos_mm[:, j_idx, 1]
    flattened_data[f'{joint_name}__pz'] = pos_mm[:, j_idx, 2]
    # Rotation (Quaternion) - Mapping to __qx, __qy, __qz, __qw
    flattened_data[f'{joint_name}__qx'] = q_global[:, j_idx, 0]
    flattened_data[f'{joint_name}__qy'] = q_global[:, j_idx, 1]
    flattened_data[f'{joint_name}__qz'] = q_global[:, j_idx, 2]
    flattened_data[f'{joint_name}__qw'] = q_global[:, j_idx, 3]

df_clean = pd.DataFrame(flattened_data)

# --- 2. Define RUN_ID and output directory ---
RUN_ID = os.path.splitext(os.path.basename(CSV_PATH))[0]
DERIV_01 = os.path.join(PROJECT_ROOT, CONFIG['derivatives_dir'], "step_01_parse")
os.makedirs(DERIV_01, exist_ok=True)

# --- 3. Create THE ULTIMATE ENHANCED REPORT ---
# כאן אנחנו מוודאים שכל שדה מהרשימה שלך נכנס
enhanced_report = {
    "identity": {
        "run_id": RUN_ID,
        "processing_timestamp": pd.Timestamp.now().strftime('%Y-%m-%d %H:%M'),
        "pipeline_version": "v2.5_robust_audit",
        "csv_source": CSV_PATH
    },
    "raw_data_quality": {
        "total_frames": len(df_clean),
        "missing_data_percent": loader_report['data_quality']['nan_position_percent'], # אחוז חסרים מקורי
        "sampling_rate_actual": loader_report['fps_estimated'],
        "optitrack_mean_error_mm": float(metadata.get('mean_error', 0.0)) if 'metadata' in locals() else 0.0,
        "optitrack_version": metadata.get('version', 'unknown') if 'metadata' in locals() else 'unknown'
    },
    "skeleton_info": {
        "segments_found": joints_found,
        "segments_found_count": len(joints_found),
        "segments_missing": loader_report['segments_missing_list'],
        "segments_missing_count": loader_report['segments_missing_count']
    },
    "duration_sec": loader_report['duration_sec']
}

# --- 4. Save report ---
report_path = os.path.join(DERIV_01, f"{RUN_ID}__step01_loader_report.json")
with open(report_path, 'w') as f:
    json.dump(enhanced_report, f, indent=4)

# --- 5. Summary Output ---
print(f"\n{'='*60}")
print(f"✅ STEP 01 COMPLETE: {RUN_ID}")
print(f"📊 Frames: {len(df_clean):,}")
print(f"🎬 Actual FPS: {loader_report['fps_estimated']:.2f}")
print(f"📐 Mean System Error: {enhanced_report['raw_data_quality']['optitrack_mean_error_mm']:.5f} mm")
print(f"🦴 Segments Found: {len(joints_found)}/{loader_report.get('segments_expected', 'N/A')}")
print(f"📂 Audit Report Saved: {report_path}")
print(f"{'='*60}\n")

# Display first few rows
df_clean.head()

# At the end of cells with large arrays, add:
import gc
gc.collect()

# Don't keep multiple copies of large data
# Instead of: df_backup = df_clean
# Use: df_clean.to_parquet('temp_backup.parquet')


✅ STEP 01 COMPLETE: 734_T1_P1_R1_Take 2025-12-01 02.18.27 PM
📊 Frames: 30,798
🎬 Actual FPS: 120.00
📐 Mean System Error: 0.00000 mm
🦴 Segments Found: 51/51
📂 Audit Report Saved: /Users/drorhazan/Documents/untitled folder/Gaga-mocap-Kinematics/derivatives/step_01_parse/734_T1_P1_R1_Take 2025-12-01 02.18.27 PM__step01_loader_report.json



62